# Generated by Django 3.1.2 on 2021-08-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(),
        ),
    ]
