# Generated by Django 3.1.2 on 2021-08-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums_app', '0002_auto_20210819_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(verbose_name='%m/%d/%y'),
        ),
    ]
