# Generated by Django 3.1.2 on 2021-08-19 02:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('albums_app', '0004_auto_20210819_0226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(),
        ),
    ]
